### PR TITLE
Replace google_api with duckduckgo

### PR DESCRIPTION
**Pull request by dla-010609**
Replace google_api with duckduckgo

### CODE REVIEW

**Comment by dla-010609** [comment]
Replace google_api with duckduckgo

**Comment by Appointat** [comment]
Hi @dla-010609 , set the duckduckgo as the default option. If the user don't provide the google API, then it switch to use the duckduckgo api.

**Comment by Appointat** [comment]
BTW: This PR will be reviewed when the other [PR](https://github.com/camel-ai/camel/pull/440) is merged.

**Comment by Appointat** [comment]
We will close this pr, since the DuckDuckGo feature has been merged to Camel.ai : https://github.com/camel-ai/camel/pull/440

**Comment by Appointat** [comment]
We will close this pr, since the DuckDuckGo feature has been merged to Camel.ai : https://github.com/camel-ai/camel/pull/440

**Pull request closed without merging**
